---

- debug:
   msg: "Default VPC ID from another role: {{ default_vpc_id }}" 
- name: security group for rds instance inside default vpc
  ec2_group:
   name: rds-sg
   description: rds sg with rule descriptions
   vpc_id: "{{ default_vpc_id }}"
   region: "{{ region }}"
   rules:
    - proto: tcp
      from_port: 3306
      to_port: 3306
      cidr_ip: "{{ k8s_cidr_block }}"
      rule_desc: allow all on port 3306 from CIDR IP of k8s cluster
   tags:
    db-group: rds-sg
  register: rdssg

- rds:
   command: create
   instance_name: csye7374-backend
   db_name: csye7374_backend
   db_engine: mariadb
   engine_version: "10.3" #Pass as CLI arguement
   region: "{{ region }}"
   vpc_security_groups: "{{ rdssg.group_id }}"
   size: "20"
   instance_type: db.t3.medium
   backup_retention: "0"
   publicly_accessible: no
   username: "{{ rds_username }}" #Pass as CLI arguement
   password: "{{ rds_password }}" #Pass as CLI arguement
   wait: yes
   wait_timeout: 72000 #Setting the timeout to 20 minutes
   tags:
    dbinfo: recipedb